[build]
    command = "npm run build"
    functions = "functions-build"

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/:splat"
    status = 200
    force = true

[dev]
    functions = "functions"
    port = 8888
    targetPort = 3000